# Generated by Django 3.2.2 on 2021-05-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mensaje',
            field=models.CharField(default=2, max_length=500, verbose_name='Mensaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/upload'),
        ),
    ]
